import React from 'react'
import './publications.css'

const Publications = () => {
  return (
    <>
        <section className="publications">
            <div className="top_section">
              <div className="book">Book&nbsp;Chapters</div>
              <div className="journals">Journals</div>
              <div className="patent">Patents</div>
            </div>

            {/* book chapters */}
            <div className="book_chp">
              <h6>Book Chapters</h6>
              <ol>
                <li><a href="https://link.springer.com/chapter/10.1007/978-3-319-30019-1_9" target='_blank'>A. E. Vasdekis, G. Stephanopoulos, <span>'Single Cell Phenotypic Screening in Inverse Metabolic Engineering', in Microfluidic Methods for Molecular Biology</span> Springer (2016).</a></li>
              </ol>
            </div>

            {/* journals */}
            <div className="journals_section">
              <h6>Journals</h6>
              <ol reversed>
                <li><a href="https://www.nature.com/articles/s41598-024-60057-y" target='_blank'>Jinming Zhang, Mirsaeid Sarollahi, Shirley Luckhart, Maria J. Harrison, and Andreas E. Vasdekis, <span>'Quantitative Phase Imaging by Gradient Retardance Optical Microscopy'</span>, Scientific Reports 14, 9754 (2024).</a></li>
                <li><a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/jbio.202300068" target='_blank'>Nava R. Subedi, Sergey Stolyar, Sabrina J. Tuson, Christopher J. Marx, and Andreas E. Vasdekis, <span>'Scattered-light-sheet microscopy with sub-cellular resolving power'</span>, Journal of Biophotonics e202300068 (2023).</a></li>
                <li><a href="https://www.pnas.org/doi/abs/10.1073/pnas.2210037120" target='_blank'>Lochlann Dunn, Haokun Luo, Nava R. Subedi, Ramachandran Kasu, Armando G. McDonald, Demetrios N. Christodoulides, and Andreas E. Vasdekis, <span>'Video-rate Raman-based metabolic imaging by Airy light-sheet illumination and photon-sparse detection'</span>, Proceedings of the National Academy of Sciences 120, e2210037120 (2023).</a></li>
                <li><a href="https://www.nature.com/articles/s42003-022-03348-2" target='_blank'>S. Nemati, A. Singh, S. D. Dhuey, A. McDonald, D. M. Weinreich, A. E. Vasdekis, <span>'Density fluctuations, homeostasis, and reproduction effects in bacteria'</span>, Communications Biology 5, 397 (2022).</a></li>
                <li><a href="https://www.sciencedirect.com/science/article/abs/pii/S1878818121003376?dgcid=coauthor#gs3" target='_blank'>G. Kukal, A. E. Vasdekis, A. G. McDonald, <span>'Raman-probes for monitoring metabolites and nutrient fate in Yarrowia lipolytica using deuterated glucose'</span>, Biocatalysis and Agricultural Biotechnology 39, 102241 (2022).</a></li>
                <li><a href="https://pubs.acs.org/doi/abs/10.1021/acsphotonics.1c01142" target='_blank'>T. Sanchez, N. R. Subedi, C. Thompson, L. Sheneman, A. E. Vasdekis, <span>'Photon-Sparse, Poisson Light-Sheet Microscopy'</span>, ACS Photonics 8, 2876 (2021).</a></li>
                <li><a href="https://opg.optica.org/oe/fulltext.cfm?uri=oe-29-20-31941&id=459719" target='_blank'>N. R. Subedi, S. Yaraghi, P. S. Jung, G. Kukal, A. G. McDonald, D. N. Christodoulides, A. E. Vasdekis, <span>'Airy light-sheet Raman imaging'</span>, Optics Express, 29, 31941 (2021).</a></li>
                <li><a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0249196" target='_blank'>L. Sheneman, Gregory Stephanopoulos, A. E. Vasdekis, <span>'Deep Learning Classification of Lipid Droplets in Quantitative Phase Images'</span>, PLOS ONE 16, e0249196 (2021).</a></li>
                <li><a href="https://www.nature.com/articles/s41598-020-76730-x" target='_blank'>N. R. Subedi, P. S. Jung, E. L. Bredeweg, S. Nemati, S. E. Baker, D. N. Christodoulides, A. E. Vasdekis, <span>'Integrative quantitative-phase and airy light-sheet imaging'</span>, Scientific Reports 10, 20150 (2020).</a></li>
                <li><a href="https://wires.onlinelibrary.wiley.com/doi/abs/10.1002/wsbm.1512" target='_blank'>A. E. Vasdekis, A. Singh, <span>'Microbial Metabolic Noise'</span>, Wiley Systems Biology and Medicine, doi: 10.1002/wsbm.1512 (2020).</a></li>
                <li><a href="https://www.nature.com/articles/s41467-019-08717-w" target='_blank'>A.E. Vasdekis, H. Alanazi, A. M. Silverman, C. J. Williams, A. J. Canul, J. B. Cliff, A. C. Dohnalkova, G. Stephanopoulos, <span>'Eliciting the impacts of cellular noise on metabolic trade-offs by quantitative mass imaging'</span>, Nature Communications 10, 848 (2019).</a></li>
                <li><a href="https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008458" target='_blank'>J. A. Lee, S. Riazi, S. Nemati, J. V. Bazurto, A. E. Vasdekis, B. J. Ridenhour, C. H. Remien, C. J. Marx, <span>'Microbial phenotypic heterogeneity in response to a metabolic toxin: Continuous, dynamically shifting distribution of formaldehyde tolerance in Methylobacterium extorquens populations'</span>, PLoS Genetics 15, e1008458 (2019).</a></li>
                <li><a href="https://www.cambridge.org/core/journals/journal-of-materials-research/article/abs/an-unexpected-phase-transformation-of-ceria-nanoparticles-in-aqueous-media/D03C29587551E66198F7181CB329F54D" target='_blank'>S. V. N. T. Kuchibhatla, A. S. Karakoti, A. E. Vasdekis, C. F. Windish S. Seal, S. Thevuthasan, D. R. Baer, <span>'Influence of Particle size on the reactive transformation of ceria nanoparticles'</span> Journal of Material Research 34, 465 (2018).</a></li>
                <li><a href="https://validate.perfdrive.com/fb803c746e9148689b3984a31fccd902/?ssa=9389b037-3874-4121-9e32-a7adb4fd87bc&ssb=83566257774&ssc=https%3A%2F%2Fiopscience.iop.org%2Farticle%2F10.1088%2F1361-6463%2Faaedf4%2Fpdf&ssi=cadfe349-cnvj-4a1f-9afb-1babe4641716&ssk=botmanager_support@radware.com&ssm=04769419655432448105343824425573&ssn=8aeaa8cb259f63edd57e0a8b4e741923df71fc9098b8-0051-497e-a4151f&sso=afdb4891-814c8df130555a8c2ba9029db2d98c7ae4a87d91fecce702&ssp=14981540861747930338174796483327761&ssq=01578877896964292872578969530058911248762&ssr=NDcuMjMxLjExNS4yMQ==&sst=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/136.0.0.0%20Safari/537.36&ssu=&ssv=&ssw=&ssx=eyJfX3V6bWYiOiI3ZjYwMDBlZmNiMmM3Mi01M2RkLTQwNjQtYjFiZi04MWUxMTA3YTUwNDkxNzQ3OTc4OTY5NzIwMC04OGE5ODEzNjczY2U1MDNlMTAiLCJyZCI6ImlvcC5vcmciLCJ1em14IjoiN2Y5MDAwNzllMGNkZTMtZWM2MC00ZmRlLTg3NDMtOTk5NTBiN2Q3NDE5MS0xNzQ3OTc4OTY5NzIwMC1jZmQ5YWEyYzBiNjQwMmRlMTAifQ==" target='_blank'>A. Guglielmelli, S. H Nemati, A. E. Vasdekis, L. De Sio, <span>Stimuli responsive diffraction gratings in soft-composite materials'</span> J. Phys. D: Appl. Phys. 52, 053001 (2018).</a></li>
                <li><a href="http://aip.scitation.org/doi/full/10.1063/1.4979575" target='_blank'>S. H. Nemati, D. A. Liuy, A. J. Canul, A. E. Vasdekis, <span>'Solvent immersion imprint lithography: A High-Performance, Semi-Automated Protocol'</span>, Biomicrofluidics 11, 024111 (2017).</a></li>
                <li><a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0168889" target='_blank'>A. E. Vasdekis, A. M. Silverman, G. Stephanopoulos, <span>'Exploiting Bioprocessing Fluctuations to Elicit the Mechanisms of de-novo Lipogenesis in Yarrowia lipolytica'</span>, PLOS ONE 12, e0168889 (2017).</a></li>
                <li><a href="https://onlinelibrary.wiley.com/doi/10.1002/cyto.a.23099/abstract;jsessionid=61E426213570041DE07FCD55E119FFD5.f01t03" target='_blank'>H. Alanazi, A. J. Canul, J. Quimby, A. Garman, A. E. Vasdekis, <span>'Robust Microbial Cell Segmentation by Optical-Phase Threhsolding with Minimal Processing Requirements'</span>, Cytometry 91, 443 (2017).</a></li>
                <li><a href="https://pubs.acs.org/doi/abs/10.1021/acs.jpcb.6b05565" target='_blank'>T. - M. Chang, S. S. Xantheas, A. E. Vasdekis, <span>'Mesoscale Polymer Dissolution Probed by Raman Spectroscopy and Molecular Simulations'</span>, Journal of Physical Chemistry B 120, 10581-10587 (2016).</a></li>
                <li><a href="https://onlinelibrary.wiley.com/doi/full/10.1002/polb.24091" target='_blank'>D. A. Liuy, S. H. Nemati, A. E. Vasdekis, <span>'Solvent Assisted Prototyping of Microfluidics and Optofluidc Microsystems'</span> Journal of Polymer Science Part B: Polymer Physics 54, 1681-1686 (2016).</a></li>
                <li><a href="http://scitation.aip.org/content/aip/journal/app/1/2/10.1063/1.4947228" target='_blank'>D. Psaltis, A. E. Vasdekis, J.-W. Choi, <span>'The Optofluidics of Plants'</span>, APL Photonics 1, 020901 (2016).</a></li>
                <li><a href="https://www.nature.com/articles/srep17689" target='_blank'>A. E. Vasdekis, A. M. Silverman, G. Stephanopoulos, <span>'Origins of Cell-to-Cell Bioprocessing Diversity and Implications of the Extracellular Environment Revealed at the Single-Cell Level'</span>, Scientific Reports 5 , 17689 (2015).</a></li>
                <li><a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/polb.23961" target='_blank'>J. S. Moore, S. S. Xantheas, J. W. Grate, T. W. Wietsma, E. Gratton, A. E. Vasdekis, <span>'Modular Polymer Biosensors by Solvent Immersion Imprint Lithography'</span>, Journal of Polymer Science Part B 54, 98-103 (2015).</a></li>
                <li><a href="https://www.sciencedirect.com/science/article/abs/pii/S1096717614001219" target='_blank'>A. E. Vasdekis, G. Stephanopoulos, <span>'A Review of Methods to Study Single Cell Metabolism and Bioenergetics'</span>, Metabolic Engineering 27, 115-135 (2015).</a></li>
                <li><a href="https://pubs.acs.org/doi/abs/10.1021/acs.bioconjchem.5b00048" target='_blank'>J. W. Grate, K.-F. Mo, Y. Shin, A. E. Vasdekis, M. G. Warner, R. T. Kelly, G. Orr, D. Hu, K. J. Dehoff, F. J. Brockman, M. J. Wilkins, <span>'Alexa Fluor-Labeled Fluorescent Cellulose Nanocrystals for Bioimaging Solid Cellulose in Spatially Structured Microenvironments'</span>, Bioconjugate Chemistry 26, 593-601 (2015).</a></li>
                <li><a href="https://pubs.rsc.org/en/Content/ArticleLanding/2014/LC/C4LC00226A#!divAbstract" target='_blank'>A. E. Vasdekis, M. J. Wilkins, J. W. Grate, R. T. Kelly, A. E. Konopka, S. S. Xantheas, T.-M. Chang, <span>'Solvent Immersion Lithography'</span> Lab on a Chip 14, 2072-2080 (2014).</a></li>
                <li><a href="https://pubs.rsc.org/en/Content/ArticleLanding/2013/RA/c3ra40369f#!divAbstract" target='_blank'>A. E. Vasdekis, <span>'Single microbe trap and release in sub-microfluidics'</span>, RSC Advances 3, 6343 (2013).</a></li>
                <h6 className='prior'>Prior (postdoc - graduate student)</h6>
                <li><a href="https://www.annualreviews.org/content/journals/10.1146/annurev-matsci-071312-121724" target='_blank'>A. E. Vasdekis, E. A. Scott, S. Roke, J. A. Hubbell, D. Psaltis, <span>'Vesicle Photonics'</span>, Annual Reviews of Materials Research 43, 283-305 (2013).</a></li>
                <li><a href="https://pubs.rsc.org/en/Content/ArticleLanding/2013/LC/c3lc50501d#!divAbstract" target='_blank'>J. G. Cuennet, A. E. Vasdekis, D. Psaltis, <span>'Optofluidic tunable color filters and spectroscopy based on liquid crystal microflows’</span>, Lab on a Chip 13, 2721 (2013).</a></li>
                <li><a href="https://opg.optica.org/oe/fulltext.cfm?uri=oe-21-25-30984&id=275913" target='_blank'>G. P. J. Laporte, D. B. Conkey, A. E. Vasdekis, R. Piestum, D. Psaltis, <span>'Double-helix enhanced axial localization in STED nanoscopy'</span> Optics Express 21, 30984 (2013).</a></li>
                <li><a href="https://pubs.rsc.org/en/Content/ArticleLanding/2013/TC/C3TC31272K#!divAbstract" target='_blank'>L. De Sio, G. Palermo, V. Caliqiuri, A. E. Vasdekis, A. Pane, J. - W. Choi, L. Muffi, M. Niklaus, H. R. Hsea, C. Umeton, <span>'Electro and pressure tunable cholesteric liquid crystal devices based on ion-implanted flexible substrates'</span>, J. Materials Chemistry C 1, 7798 (2013).</a></li>
                <li><a href="https://www.tandfonline.com/doi/abs/10.1080/15421406.2013.789716#preview" target='_blank'>M. Romito, L. De Sio, A. E. Vasdekis, C. Umeton, <span>'Optofluidic microstructures containing liquid crystals'</span>, Molecular Crystals and Liquid Crystals 576, 135 (2013).</a></li>
                <li><a href="https://pubs.acs.org/doi/abs/10.1021/nn302122h" target='_blank'>A. E. Vasdekis, E. A. Scott, C. P. O’Neil, D. Psaltis, J. A. Hubbell, <span>‘Precise cytosolic delivery and cellular tracking based on optofluidic polymersome rupture’</span>, ACS Nano 6, 7850 (2012).</a></li>
                <li><a href="https://pubs.rsc.org/en/Content/ArticleLanding/2012/LC/c2lc40481h#!divAbstract" target='_blank'>W. Z. Song, A. E. Vasdekis, D. Psaltis, <span>‘Elastomer based optofluidic devices’</span>, Lab-on-a-Chip 12, 3590 (2012).</a></li>
                <li><a href="https://pubs.rsc.org/en/Content/ArticleLanding/2012/LC/c2lc40668c#!divAbstract" target='_blank'>L. De Sio, M. Romito, M. Giocondo, A. E. Vasdekis, A. De Luca, C. Umeton, <span>‘Electroswitchable polydimethilsiloxane based optofluidics’</span>, Lab-on-a-Chip 12, 3760 (2012).</a></li>
                <li><a href="https://www.nature.com/articles/nphoton.2011.18" target='_blank'>J. G. Cuennet, A. E. Vasdekis (1st equivalent author), L. De Sio, D. Psaltis, <span>'Optofluidic modulator based on peristaltic nematogen microflows'</span>, Nature Photonics 5, 235-235 (2011).</a></li>
                <li><a href="https://www.mdpi.com/1422-0067/12/8/5135" target='_blank'>L. De Sio, A. E. Vasdekis, J. R. Cuennet, A. De Luca, A. Pane, D. Psaltis, <span>‘SiO deposition on PDMS gratings for enhanced optical switching’</span>, Optics Express 19, 23532 (2011).</a></li>
                <li><a href="https://www.mdpi.com/1422-0067/12/8/5135" target='_blank'>A. E. Vasdekis, G. P. J. Laporte <span>'Enhancing single molecule imaging in optofluidics and microfluidics'</span>, invited review, International Journal of Molecular Science 12, 5135-5156 (2011).</a></li>
                <li><a href="https://www.worldscientific.com/doi/abs/10.1142/S0218863511006303" target='_blank'>J. G. Cuennet, A. E. Vasdekis, L. De Sio, D. Psaltis, <span>'Light modulation enabled by liquid crystal microflows'</span>, Journal of Non-Linear Optics and Materials 20, 397-404 (2011).</a></li>
                <li><a href="https://pubs.acs.org/doi/abs/10.1021/bm901453u" target='_blank'>A. E. Vasdekis, C. P. O'Neil, J. A. Hubbell, D. Psaltis, <span>'Microfluidic Assays for DNA Manipulation Based on a Block-copolymer Immobilization Strategy'</span>, Biomacromolecules 11, 827 (2010).</a></li>
                <li><a href="http://scitation.aip.org/content/aip/journal/apl/96/13/10.1063/1.3377801" target='_blank'>L. De Sio, J. G. Cuennet, A. E. Vasdekis, D. Psaltis, <span>'All Optical Switching in an Optofluidic PDMS-Liquid Crystal grating defined by cast-molding'</span>, Applied Physics Letters 96, 131112 (2010).</a></li>
                <li><a href="https://authors.library.caltech.edu/14354/" target='_blank'>W.Z. Song, A. E. Vasdekis, Z. Li, D. Psaltis, <span>'Optofluidic evanescent dye laser based on a distributed feedback circular grating resonator'</span>, Applied Physics Letters 94, 161111 (2009).</a></li>
                <li><a href="http://scitation.aip.org/content/aip/journal/apl/94/5/10.1063/1.3079799" target='_blank'>W.Z. Song, A. E. Vasdekis, Z. Li, D. Psaltis, <span>'Low-order distributed optofluidic dye laser with reduced threshold'</span>, Applied Physics Letters 94, 051117 (2009).</a></li>
                <li><a href="https://advanced.onlinelibrary.wiley.com/doi/abs/10.1002/adma.200801930" target='_blank'>D. Amarasinghe, A. Ruseckas, A.E. Vasdekis, G.A. Turnbull, I.D.W. Samuel, <span>'High gain broadband solid state optical amplifier using a semiconducting polymer'</span>, Advanced Materials 20, 107-110 (2008).</a></li>
                <li><a href="https://pubs.aip.org/aip/apl/article-abstract/92/8/083305/335076/Picosecond-gain-switching-of-an-organic?redirectedFrom=fulltext" target='_blank'>D. Amarasinghe, A. Ruseckas, A.E. Vasdekis, G.A. Turnbull, I.D.W. Samuel, <span>'Picosecond gain switching of an organic semiconductor optical amplifier'</span>, Applied Physics Letters 92, 083305 (2008).</a></li>
                <li><a href="http://scitation.aip.org/content/aip/journal/apl/91/5/10.1063/1.2764553" target='_blank'>A.E. Vasdekis, S. Moore, A. Ruseckas, T.F. Krauss, I.D.W. Samuel, G.A. Turnbull, <span>‘Silicon based organic semiconductor laser’</span>,  Applied Physics Letters 91, 051124 (2007).</a></li>
                <li><a href="http://scitation.aip.org/content/aip/journal/apl/91/1/10.1063/1.2753542" target='_blank'>D. Amarasinghe, A. Ruseckas, A.E. Vasdekis, M. Goossens, G.A. Turnbull, I.D.W. Samuel, <span>'Amplification of optical pulse sequences at a high repetition rate in a polymer slab waveguide'</span>, Applied Physics Letters 91, 011105 (2007).</a></li>
                <li><a href="https://opg.optica.org/oe/fulltext.cfm?uri=oe-15-7-3962&id=131616" target='_blank'>A.E. Vasdekis, G.E. Town, G.A. Turnbull, I.D.W. Samuel, <span>‘Fluidic fibre dye lasers’</span>, Optics Express 15, 3962 (2007).</a></li>
                <li><a href="https://opg.optica.org/oe/fulltext.cfm?uri=oe-14-20-9211&id=114597" target='_blank'>A.E. Vasdekis, G. Tsiminis, J.-C. Ribierre, L.O. Faolain, T.F. Krauss, G.A. Turnbull, I.D.W. Samuel, <span>'Diode pumped distributed Bragg reflector lasers based on a dye to polymer energy transfer blend'</span>, Optics Express 14, 9211 (2006).</a></li>
                <li><a href="http://scitation.aip.org/content/aip/journal/apl/89/20/10.1063/1.2390649" target='_blank'>D. Amarasinghe, A. Ruseckas, A.E. Vasdekis, M. Goossens, G.A. Turnbull, I.D.W. Samuel, <span>'Broadband solid state optical amplifier based on a semiconducting polymer'</span>, Applied Physics Letters 89, 201119 (2006).</a></li>
                <li><a href="http://scitation.aip.org/content/aip/journal/apl/86/16/10.1063/1.1898430" target='_blank'>A.E. Vasdekis, G.A. Turnbull, I.D.W. Samuel, P. Andrew and W.L. Barnes <span>‘Low threshold edge emitting polymer distributed’</span>, Applied Physics Letters 86, 161102 (2005).</a></li>
              </ol>
            </div>

            {/* Patents */}
            <div className="patents_section">
              <h6>Patents</h6>
              <ol>
                <li><a href="https://patents.google.com/patent/US20210285883A1/en" target='_blank'>A. E. Vasdekis, N. R. Subedi, S. Nemati, <span>'Integrated imaging assembly and method for using'</span>, US  Patent 11,726,043, 2023/‌8/‌15.</a></li>
                <li><a href="https://worldwide.espacenet.com/searchResults?ST=singleline&locale=en_EP&submitted=true&DB=worldwide.espacenet.com&query=vasdekis" target='_blank'>A. E. Vasdekis, M. J. O'Hara, J. W. Grate, <span>'Device, System and Method of Making a Sensor'</span>, U.S. Patent No. 14/710,907 (2015).</a></li>
                <li><a href="https://worldwide.espacenet.com/searchResults?ST=singleline&locale=en_EP&submitted=true&DB=worldwide.espacenet.com&query=vasdekis" target='_blank'>A. E Vasdekis, J. G. Cuennet, D. Psaltis, <span>'Light Filter and Method for using such a filter’</span>, International Patent No. WO2011IB54217 20110926 (2012).</a></li>
              </ol>
            </div>
            
        </section>
    </>
  )
}

export default Publications